# Site settings
title: Clouder::Blogger
baseurl: ""
url: http://blog.clouder.jp
twitter_username: clouder
github_username:  yoshiki

# Build settings
markdown: kramdown
lsi: false
incremental: true
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
gems:
  - jekyll-paginate
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - .gitignore
  - .bundle
  - .git
  - LICENSE
  - CNAME
