# Site settings
title: Clouder::Blogger
baseurl: ""
url: http://blog.clouder.jp
twitter_username: clouder
github_username:  yoshiki

# Build settings
lsi: false
safe: true
incremental: false
highlighter: rouge
permalink: /:year/:month/:day/:title/
gems:
  - jekyll-sitemap
exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - .gitignore
  - .bundle
  - .git
  - LICENSE
  - CNAME
