# Site settings
title: Clouder::Blogger
baseurl: ""
url: http://blog.clouder.jp
twitter_username: clouder
github_username:  yoshiki

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
lsi: false
incremental: false
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10
gems:
  - jekyll-paginate
